[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = ".netlify/functions"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["404"]}

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
